name:   Post Welcome action comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  build:
    name: Post Welcome action comment
    runs-on: ubuntu-latest
    steps:
      - run: echo "Welcome to repo!!"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.events.pull_request.html_url }}